apiVersion: v1
kind: Service
metadata:
  name: {{ include "password-generator-chart.fullname" . }}-{{ .Values.environment }}
  labels:
    {{- include "password-generator-chart.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.externalPort }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "password-generator-chart.selectorLabels" . | nindent 4 }}
    environment: {{ .Values.environment }}
